apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-world
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
